version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_USER: 'emin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

#  pdf-service:
#    image: pdf-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

volumes:
  my-db: